[phases.setup]
nixPkgs = ["ffmpeg", "curl"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python telegram_bot.py"
